[project]
name = "smf-jewels-backend"
version = "0.1.0"
description = "SMF Jewels FastAPI backend"

dependencies = [
  "fastapi",
  "uvicorn",
  "pymongo",
  "python-dotenv"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
